*** Module defining the type for agent identifiers

*** Copyright (C) 2021  Massimiliano Mirelli
***                     massimilianomirelli.mm@gmail.com
*** This program is free software; you can redistribute it and/or
*** modify it under the terms of the GNU General Public License
*** as published by the Free Software Foundation; either version 2
*** of the License, or (at your option) any later version.

*** This program is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*** GNU General Public License for more details.

*** You should have received a copy of the GNU General Public License
*** along with this program; if not, write to the Free Software
*** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


fmod AGENT-ID is 
  sort Agent-Id .
endfm

view Agent-Id from TRIV to AGENT-ID is
  sort Elt to Agent-Id .
endv

fmod AGENT-ID-SETS is
    including AGENT-ID .
    including SET{Agent-Id} .
    ops A, B, C, D, Att, Vic, 
           Oth, A-1 : -> Agent-Id [ctor] .
    
    op dummyAId : Nat -> Agent-Id [ctor] .
    ops DEP LED LOR : Nat -> Agent-Id [ctor] .

    ops agents : -> Set{Agent-Id} .
    eq agents = A, B, C, D .
endfm

