*** Copyright (C) 2021  Massimiliano Mirelli
***                     massimilianomirelli.mm@gmail.com
*** This program is free software; you can redistribute it and/or
*** modify it under the terms of the GNU General Public License
*** as published by the Free Software Foundation; either version 2
*** of the License, or (at your option) any later version.

*** This program is distributed in the hope that it will be useful,
*** but WITHOUT ANY WARRANTY; without even the implied warranty of
*** MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
*** GNU General Public License for more details.

*** You should have received a copy of the GNU General Public License
*** along with this program; if not, write to the Free Software
*** Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.


--- number of all canonical final states -> 7
search in LIQUIDATOR-TEST :
   (test12) =>! X:closedConfiguration .
--- number of canonical final states satisfying the where
--- LED(0)'s collateralization is 0.0
--- expected = 7 
search in LIQUIDATOR-TEST :
   (test12) =>! X:closedConfiguration
   such that 
        ((X:closedConfiguration).config).C(LED(0)) == 0.0  .
